/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jdbc;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;

/**
 *
 * @author Kiruthika
 */
public class userpanel extends javax.swing.JFrame {

    Connection conn=null;
    OraclePreparedStatement pst=null;
    OracleResultSet rs=null;
    DefaultTableModel model;
    DefaultTableModel model2;
    DefaultTableModel model3;
    DefaultTableModel model4;
    DefaultListModel m=new DefaultListModel();
    String g1="AAA",g2="AAA",g3="AAA",g4="AAA",g5="AAA",g6="AAA",o="ASC";
    int por,nor,por1,nor1;
    
    /**
     * Creates new form userpanel
     */
    public userpanel() {
        initComponents();
        Toolkit toolkit=getToolkit();
        Dimension size=toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
    }

    public void select()
    {
       
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        welcome = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        centre = new javax.swing.JPanel();
        home = new javax.swing.JPanel();
        recommend = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel35 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        preference = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        rate = new javax.swing.JPanel();
        text = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        bookname = new javax.swing.JTextField();
        bookid = new javax.swing.JTextField();
        author = new javax.swing.JTextField();
        genre = new javax.swing.JTextField();
        publisher = new javax.swing.JTextField();
        edition = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        language = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel28 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jSlider1 = new javax.swing.JSlider();
        jLabel6 = new javax.swing.JLabel();
        user = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jSlider2 = new javax.swing.JProgressBar();
        jSlider3 = new javax.swing.JProgressBar();
        jSlider4 = new javax.swing.JProgressBar();
        jSlider5 = new javax.swing.JProgressBar();
        jSlider6 = new javax.swing.JProgressBar();
        jSlider7 = new javax.swing.JProgressBar();
        jLabel19 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        viewbook = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BOOK RECOMMENDER");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcome.setFont(new java.awt.Font("Felix Titling", 0, 36)); // NOI18N
        jPanel2.add(welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 480, 50));

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\New Pc\\Pictures\\user.png")); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 10, 90, 90));

        jTextField1.setText("jTextField1");
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 50, -1, -1));

        jLabel55.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        jPanel2.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 440, 30));

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(255, 204, 102));
        jPanel3.setPreferredSize(new java.awt.Dimension(180, 308));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 204, 102));
        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButton1.setText("RATE");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(255, 204, 102)));
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 220, 50));

        jButton2.setBackground(new java.awt.Color(255, 204, 102));
        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jButton2.setText("RECOMMENDED BOOKS");
        jButton2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(255, 204, 102)));
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 50, 210, 50));

        jButton3.setBackground(new java.awt.Color(255, 204, 102));
        jButton3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jButton3.setText("USERS PREFERENCES");
        jButton3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(255, 204, 102)));
        jButton3.setOpaque(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 100, 200, 50));

        jButton7.setBackground(new java.awt.Color(255, 204, 102));
        jButton7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jButton7.setText("VIEW ALL BOOKS");
        jButton7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(255, 204, 102)));
        jButton7.setOpaque(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 150, 210, 50));

        jButton9.setBackground(new java.awt.Color(255, 204, 102));
        jButton9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jButton9.setText("LOG OUT");
        jButton9.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(255, 204, 102)));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 200, 210, 50));

        jPanel1.add(jPanel3, java.awt.BorderLayout.LINE_START);

        centre.setLayout(new java.awt.CardLayout());

        home.setBackground(new java.awt.Color(255, 255, 204));
        home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        centre.add(home, "card2");

        recommend.setBackground(new java.awt.Color(255, 255, 255));
        recommend.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        recommend.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, 60, 20));
        recommend.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 260, 30));

        jLabel35.setText("jLabel35");
        recommend.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 480, 30));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable2);

        recommend.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 1030, 319));

        jLabel21.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel21.setText("RECOMMENDED BOOKS");
        recommend.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\New Pc\\Pictures\\background\\abstract-light-orange-watercolor-background-spring-summer-theme-copy-space-53946934.jpg")); // NOI18N
        recommend.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 610));

        centre.add(recommend, "card3");

        preference.setBackground(new java.awt.Color(255, 255, 255));
        preference.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel7.setText("genre preferred by most of the users");
        preference.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 320, 34));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        preference.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 70, 180, 30));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(jTable4);

        preference.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 180, 710, 250));

        jLabel20.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel20.setText("BOOKS WITH HIGHEST AVERAGE RATING");
        preference.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\New Pc\\Pictures\\background\\abstract-light-orange-watercolor-background-spring-summer-theme-copy-space-53946934.jpg")); // NOI18N
        preference.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 640));

        centre.add(preference, "card4");

        rate.setBackground(new java.awt.Color(255, 255, 255));
        rate.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textActionPerformed(evt);
            }
        });
        text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textKeyTyped(evt);
            }
        });
        rate.add(text, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 230, 30));

        jButton5.setText("SELECT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        rate.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, -1, -1));

        list.setBackground(new java.awt.Color(255, 255, 153));
        list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(list);

        rate.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 230, 210));

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel5.setText("BOOK NAME");
        rate.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel8.setText("ISBN");
        rate.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel9.setText("AUTHOR");
        rate.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel10.setText("GENRE");
        rate.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel11.setText("PUBLISHER");
        rate.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel12.setText("EDITION");
        rate.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel13.setText("RATE");
        rate.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, -1, -1));
        rate.add(bookname, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 80, 111, -1));
        rate.add(bookid, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, 111, -1));
        rate.add(author, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 110, 111, -1));
        rate.add(genre, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 150, 111, -1));

        publisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publisherActionPerformed(evt);
            }
        });
        rate.add(publisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 190, 111, -1));

        edition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editionActionPerformed(evt);
            }
        });
        rate.add(edition, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, 111, -1));

        jLabel14.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel14.setText("Average rating");
        rate.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel22.setText("BOOK NAME");
        rate.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel15.setText("Total ratings");
        rate.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel16.setText("LANGUAGE");
        rate.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, -1, -1));
        rate.add(language, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 270, 111, -1));

        jButton6.setBackground(new java.awt.Color(255, 153, 51));
        jButton6.setText("RATE");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        rate.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel26.setText("POSITIVE REVIEWS ");
        rate.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, -1, -1));

        jLabel27.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel27.setText("NEGATIVE REVIEWS");
        rate.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, -1, -1));

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane8.setViewportView(jTextArea3);

        rate.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 280, 120));

        jLabel28.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel28.setText("COMMENT");
        rate.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, -1, -1));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        rate.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 410, 170, -1));

        jSlider1.setMajorTickSpacing(1);
        jSlider1.setMaximum(5);
        jSlider1.setMinimum(1);
        jSlider1.setPaintLabels(true);
        jSlider1.setToolTipText("");
        jSlider1.setValue(1);
        jSlider1.setPreferredSize(new java.awt.Dimension(200, 30));
        rate.add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, 140, 40));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\New Pc\\Pictures\\background\\abstract-light-orange-watercolor-background-spring-summer-theme-copy-space-53946934.jpg")); // NOI18N
        rate.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 610));

        centre.add(rate, "card5");

        user.setBackground(new java.awt.Color(255, 255, 255));
        user.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        user.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, 160));

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel2.setText("BOOKS RATED");
        user.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel1.setText("MOST PREFERRED GENRE");
        user.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 290, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel3.setText("MOST PREFERRED AUTHOR");
        user.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        user.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 320, 240, 180));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        user.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 60, 240, 160));

        jPanel6.setBackground(new java.awt.Color(255, 255, 204));
        jPanel6.setLayout(null);

        jLabel29.setText("DRAMA");
        jPanel6.add(jLabel29);
        jLabel29.setBounds(20, 30, 80, 20);

        jLabel30.setText("POETRY");
        jPanel6.add(jLabel30);
        jLabel30.setBounds(19, 60, 80, 14);

        jLabel31.setText("HORROR");
        jPanel6.add(jLabel31);
        jLabel31.setBounds(20, 90, 90, 14);

        jLabel32.setText("CRIME");
        jPanel6.add(jLabel32);
        jLabel32.setBounds(20, 120, 80, 14);

        jLabel33.setText("HISTORICAL");
        jPanel6.add(jLabel33);
        jLabel33.setBounds(20, 150, 100, 14);

        jLabel34.setText("COMICS");
        jPanel6.add(jLabel34);
        jLabel34.setBounds(20, 180, 80, 14);

        jLabel36.setText("0");
        jPanel6.add(jLabel36);
        jLabel36.setBounds(500, 30, 50, 14);

        jLabel37.setText("0");
        jPanel6.add(jLabel37);
        jLabel37.setBounds(500, 60, 70, 14);

        jLabel38.setText("0");
        jPanel6.add(jLabel38);
        jLabel38.setBounds(500, 90, 50, 14);

        jLabel39.setText("0");
        jPanel6.add(jLabel39);
        jLabel39.setBounds(500, 120, 50, 14);

        jLabel40.setText("0");
        jPanel6.add(jLabel40);
        jLabel40.setBounds(500, 150, 50, 14);

        jLabel41.setText("0");
        jPanel6.add(jLabel41);
        jLabel41.setBounds(500, 180, 60, 14);
        jPanel6.add(jSlider2);
        jSlider2.setBounds(110, 30, 340, 20);
        jPanel6.add(jSlider3);
        jSlider3.setBounds(110, 60, 340, 20);
        jPanel6.add(jSlider4);
        jSlider4.setBounds(110, 90, 340, 20);
        jPanel6.add(jSlider5);
        jSlider5.setBounds(110, 120, 340, 20);
        jPanel6.add(jSlider6);
        jSlider6.setBounds(110, 150, 340, 20);
        jPanel6.add(jSlider7);
        jSlider7.setBounds(110, 180, 340, 20);

        user.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 570, 230));

        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\New Pc\\Pictures\\background\\abstract-light-orange-watercolor-background-spring-summer-theme-copy-space-53946934.jpg")); // NOI18N
        user.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 770));

        centre.add(user, "card6");

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 204, 153));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCheckBox1.setText("DRAMA");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel5.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 100, -1));

        jCheckBox2.setText("POETRY");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel5.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 100, -1));

        jCheckBox3.setText("HORROR");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jPanel5.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 100, -1));

        jCheckBox4.setText("CRIME");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        jPanel5.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 100, -1));

        jCheckBox5.setText("HISTORICAL");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });
        jPanel5.add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 100, -1));

        jCheckBox7.setText("COMICS");
        jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox7ActionPerformed(evt);
            }
        });
        jPanel5.add(jCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 100, -1));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, 160, 200));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jTable3);

        jPanel4.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 570, 450));

        viewbook.setBackground(new java.awt.Color(255, 204, 153));

        jRadioButton1.setText("ASCENDING");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("DESCENDING");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout viewbookLayout = new javax.swing.GroupLayout(viewbook);
        viewbook.setLayout(viewbookLayout);
        viewbookLayout.setHorizontalGroup(
            viewbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewbookLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(viewbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRadioButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        viewbookLayout.setVerticalGroup(
            viewbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewbookLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jRadioButton1)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton2)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel4.add(viewbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, 160, 110));

        jLabel23.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel23.setText("VIEW BOOKS");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        jButton8.setText("VIEW");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 50, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel24.setText("FILTER BY");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel25.setText("SORT BY BOOK NAME");
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 320, -1, -1));

        jPanel7.setBackground(new java.awt.Color(255, 204, 153));
        jPanel7.setLayout(null);

        jLabel48.setBackground(new java.awt.Color(255, 255, 255));
        jLabel48.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel48.setText("RATINGS COUNT");
        jPanel7.add(jLabel48);
        jLabel48.setBounds(10, 10, 140, 23);

        jLabel49.setBackground(new java.awt.Color(255, 255, 255));
        jLabel49.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel49.setText("0");
        jPanel7.add(jLabel49);
        jLabel49.setBounds(160, 10, 50, 23);

        jLabel50.setBackground(new java.awt.Color(255, 255, 153));
        jLabel50.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 153));
        jLabel50.setText("0");
        jPanel7.add(jLabel50);
        jLabel50.setBounds(118, 60, 40, 25);

        jLabel51.setBackground(new java.awt.Color(255, 255, 0));
        jLabel51.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 102));
        jLabel51.setText("0");
        jPanel7.add(jLabel51);
        jLabel51.setBounds(118, 103, 40, 25);

        jLabel52.setBackground(new java.awt.Color(255, 204, 0));
        jLabel52.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 204, 0));
        jLabel52.setText("0");
        jPanel7.add(jLabel52);
        jLabel52.setBounds(118, 146, 40, 25);

        jLabel53.setBackground(new java.awt.Color(255, 102, 0));
        jLabel53.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 102, 0));
        jLabel53.setText("0");
        jPanel7.add(jLabel53);
        jLabel53.setBounds(118, 189, 40, 25);

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));

        jLabel43.setBackground(new java.awt.Color(255, 255, 153));
        jLabel43.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 153));
        jLabel43.setText("1 *");

        jLabel44.setBackground(new java.awt.Color(255, 255, 0));
        jLabel44.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 102));
        jLabel44.setText("2 *");

        jLabel45.setBackground(new java.awt.Color(255, 204, 0));
        jLabel45.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 204, 0));
        jLabel45.setText("3 *");

        jLabel46.setBackground(new java.awt.Color(255, 102, 0));
        jLabel46.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 102, 0));
        jLabel46.setText("4 *");

        jLabel47.setBackground(new java.awt.Color(255, 153, 51));
        jLabel47.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 51, 0));
        jLabel47.setText("5 *");

        jLabel54.setBackground(new java.awt.Color(255, 153, 51));
        jLabel54.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 51, 0));
        jLabel54.setText("0");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel43)
                .addGap(18, 18, 18)
                .addComponent(jLabel44)
                .addGap(18, 18, 18)
                .addComponent(jLabel45)
                .addGap(18, 18, 18)
                .addComponent(jLabel46)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(jLabel54))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel8);
        jPanel8.setBounds(10, 50, 200, 220);

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 88, 220, 280));

        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\New Pc\\Pictures\\background\\abstract-light-orange-watercolor-background-spring-summer-theme-copy-space-53946934.jpg")); // NOI18N
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 750));

        centre.add(jPanel4, "card7");

        jPanel1.add(centre, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1474, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        
        
       
        
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        home.setVisible(false);
        rate.setVisible(true);
        recommend.setVisible(false);
        preference.setVisible(false);
        user.setVisible(false);
        jPanel4.setVisible(false);
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        home.setVisible(false);
        rate.setVisible(false);
        user.setVisible(false);
        
        preference.setVisible(false);
        jPanel4.setVisible(false);
        model2=new DefaultTableModel();
        jTable2.setModel(model2);
        model2.addColumn("bookname");
        model2.addColumn("author");
        model2.addColumn("genre");
        model2.addColumn("publisher");
        model2.addColumn("edition");
        model2.addColumn("language");
        String u=Login.user_id.getText();
        conn = Jdbc.ConnecrDb();
        String a;
        try{
            
            if(conn!=null)
        {
            
             u=Login.user_id.getText();
                    
                    Statement state=conn.createStatement();
                    ResultSet rs=state.executeQuery("select count(u_id) from rating where u_id='"+u+"'");
                    if(rs.next())
                    jTextField1.setText(rs.getString("count(u_id)"));
                    jTextField1.setVisible(false);
                    jTextField1.setEditable(false);
                    a=jTextField1.getText();
                    int b=Integer.parseInt(a);
                    if(b<4)
                    {           
                       int c=4-b;
                       
                      //JOptionPane.showMessageDialog(null,"RATE ATLEAST "+c+" BOOKS TO VIEW RECOMMENDED BOOKS");  
                      recommend.setVisible(true);
                      jScrollPane5.setVisible(false);
                      jLabel21.setVisible(false);
                      jLabel35.setVisible(true);
                      jProgressBar1.setVisible(true);
                      jLabel35.setText("RATE ATLEAST "+c+" BOOKS TO VIEW RECOMMENDED BOOKS");
                      if(c==4){
                          jProgressBar1.setValue(0);
                          jLabel42.setText("0%");
                      }
                      if(c==3){
                          jProgressBar1.setValue(25);
                          jLabel42.setText("25%");
                      }
                      if(c==2){
                          jProgressBar1.setValue(50);
                          jLabel42.setText("50%");
                      }
                      if(c==1){
                          jProgressBar1.setValue(75);
                          jLabel42.setText("75%");
                      }
                      
                      
                    }
                
                    else
                    {
                        
                        recommend.setVisible(true);
                      jScrollPane5.setVisible(true);
                      jLabel21.setVisible(true);
                      jLabel35.setVisible(false);
                      jProgressBar1.setVisible(false);
            
            
            int i=0;
            state=conn.createStatement();
            
            rs=state.executeQuery("select * from book \n" +
"where bookname not in(select b1.bookname from book b1,rating r1 where b1.bookid=r1.b_id and r1.u_id='"+u+"') and\n" +
"genre in(\n" +
"select b.genre as genre from book b,rating r where b.bookid=r.b_id and r.u_id='"+u+"' group by b.genre\n" +
"having sum(r.rate)=(select max(sumrate) from (select b.genre,sum(r.rate) as sumrate \n" +
"from book b,rating r where b.bookid=r.b_id and r.u_id='"+u+"' group by b.genre))\n" +
")");
            
            
            
            //where genre="+a+"
            while(rs.next()){
                model2.addRow(new Object[]{
                        rs.getString("bookname"),
                        rs.getString("author"),
                        rs.getString("genre"),
                        rs.getString("publisher"),
                        rs.getString("edition"),
                        rs.getString("language")
                        
                });
            }
              rs=state.executeQuery("select * from book \n" +
"where bookname not in(select b1.bookname from book b1,rating r1 where b1.bookid=r1.b_id and r1.u_id='"+u+"') and \n" +
"author in(\n" +
"select b.author as author from book b,rating r where b.bookid=r.b_id and r.u_id='"+u+"' group by b.author\n" +
"having sum(r.rate)=(select max(sumrate) from (select b.author,sum(r.rate) as sumrate \n" +
"from book b,rating r where b.bookid=r.b_id and r.u_id='"+u+"' group by b.author))\n" +
") and \n"+
"genre not in(\n" +
"select b.genre as genre from book b,rating r where b.bookid=r.b_id and r.u_id='"+u+"' group by b.genre\n" +
"having sum(r.rate)=(select max(sumrate) from (select b.genre,sum(r.rate) as sumrate \n" +
"from book b,rating r where b.bookid=r.b_id and r.u_id='"+u+"' group by b.genre))\n" +
")");
              
                 while(rs.next()){
                model2.addRow(new Object[]{
                        rs.getString("bookname"),
                        rs.getString("author"),
                        rs.getString("genre"),
                        rs.getString("publisher"),
                        rs.getString("edition"),
                        rs.getString("language")
                        
                });
                //jTable1.getModel().setValueAt(rs.getString("genre"),i,2);
                //jTable1.getModel().setValueAt(rs.getString("author"),i,3);
                i++;
            }
        }
        }
    }catch(Exception e)
    {
        JOptionPane.showMessageDialog(null,e);
    }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        home.setVisible(false);
        rate.setVisible(false);
        recommend.setVisible(false);
        user.setVisible(false);
        preference.setVisible(true);
        jPanel4.setVisible(false);
        model3=new DefaultTableModel();
        jTable4.setModel(model3);
        model3.addColumn("bookname");
        model3.addColumn("author");
        model3.addColumn("genre");
        conn = Jdbc.ConnecrDb();
        String a=Login.user_id.getText();
            
            
            
            
            try{
                if(conn!=null)
                {
                    
                    Statement state=conn.createStatement();
                    ResultSet rs=state.executeQuery("select b.genre from book b,rating r where b.bookid=r.b_id group by b.genre\n" +
"    having avg(r.rate)=(select max(avgrate) from (select b.genre,avg(r.rate) as avgrate\n" +
"    from book b,rating r where b.bookid=r.b_id group by b.genre))");
                    if(rs.next())
                         jTextField2.setText(rs.getString("genre"));
                    jTextField2.setEditable(false);
                    
                  rs=state.executeQuery(" select bookname,author,genre from book where bookname in(\n" +
" select b.bookname from book b,rating r where b.bookid=r.b_id group by b.bookname\n" +
" having avg(r.rate)=(select max(avgrate) from (select b.bookname,avg(r.rate) as avgrate\n" +
" from book b,rating r where b.bookid=r.b_id  group by b.bookname)))\n" +
"        ");  
                    while(rs.next()){
                model3.addRow(new Object[]{
                        rs.getString("bookname"),
                        rs.getString("author"),
                        rs.getString("genre")
                        
                });
                }
                
            }
            }catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jTextArea1.setText(" ");
        jTextArea2.setText(" ");
        user.setVisible(true);
        home.setVisible(false);
        rate.setVisible(false);
        recommend.setVisible(false);
        jPanel4.setVisible(false);
        preference.setVisible(false);
        //jLabel2.setVisible(true);
        model=new DefaultTableModel();
        jTable1.setModel(model);
        model.addColumn("bookname");
        model.addColumn("rate"); 
        String u=Login.user_id.getText();
         
        conn = Jdbc.ConnecrDb();
        model.setRowCount(0);
         try{
            if(conn!=null)
        {
            int i=0;
            Statement state=conn.createStatement();
            
            ResultSet rs=state.executeQuery("select b.bookname,r.rate from book b,rating r\n" +
"where b.bookid=r.b_id and u_id='"+u+"'");
            
            
            
            //where genre="+a+"
            while(rs.next()){
                model.addRow(new Object[]{
                        rs.getString("bookname"),
                        rs.getString("rate")
                        
                });
            }
            
           rs=state.executeQuery("select b.genre as genre from book b,rating r where b.bookid=r.b_id and r.u_id='"+u+"' group by b.genre\n" +
"   having sum(r.rate)=(select max(sumrate) from (select b.genre,sum(r.rate) as sumrate\n" +
"   from book b,rating r where b.bookid=r.b_id and r.u_id='"+u+"' group by b.genre))"); 
           
            while(rs.next())
            {
                jTextArea1.append(rs.getString("genre")+"\n");
            }
            
            rs=state.executeQuery("select b.author as author from book b,rating r where b.bookid=r.b_id and r.u_id='"+u+"' group by b.author\n" +
"   having sum(r.rate)=(select max(sumrate) from (select b.author,sum(r.rate) as sumrate\n" +
"   from book b,rating r where b.bookid=r.b_id and r.u_id='"+u+"' group by b.author))"); 
           
            while(rs.next())
            {
                jTextArea2.append(rs.getString("author")+"\n");
            }
            rs=state.executeQuery("select avg(rate) from rating,book where bookid=b_id and u_id='"+u+"' AND genre='DRAMA' group by genre");
            if(rs.next())
            {
                Double a=Double.parseDouble(rs.getString("avg(rate)"));
                double ma=a*20;
                int aa=(int)Math.round(ma);
                
                jSlider2.setValue(aa);
                jLabel36.setText(rs.getString("avg(rate)"));
                
            }
            rs=state.executeQuery("select avg(rate) from rating,book where bookid=b_id and u_id='"+u+"' AND genre='POETRY' group by genre");
            if(rs.next())
            {
                Double a=Double.parseDouble(rs.getString("avg(rate)"));
                double ma=a*20;
                int aa=(int)Math.round(ma);
                
                jSlider3.setValue(aa);
                jLabel37.setText(rs.getString("avg(rate)"));
                
            }
            rs=state.executeQuery("select avg(rate) from rating,book where bookid=b_id and u_id='"+u+"' AND genre='HORROR' group by genre");
            if(rs.next())
            {
                Double a=Double.parseDouble(rs.getString("avg(rate)"));
                double ma=a*20;
                int aa=(int)Math.round(ma);
                
                jSlider4.setValue(aa);
                jLabel38.setText(rs.getString("avg(rate)"));
                
            }
            
            rs=state.executeQuery("select avg(rate) from rating,book where bookid=b_id and u_id='"+u+"' AND genre='CRIME' group by genre");
            if(rs.next())
            {
                Double a=Double.parseDouble(rs.getString("avg(rate)"));
                double ma=a*20;
                int aa=(int)Math.round(ma);
                
                jSlider5.setValue(aa);
                jLabel39.setText(rs.getString("avg(rate)"));
                
            }
            
            rs=state.executeQuery("select avg(rate) from rating,book where bookid=b_id and u_id='"+u+"' AND genre='HISTORICAL' group by genre");
            if(rs.next())
            {
                Double a=Double.parseDouble(rs.getString("avg(rate)"));
                double ma=a*20;
                int aa=(int)Math.round(ma);
                
                jSlider6.setValue(aa);
                jLabel40.setText(rs.getString("avg(rate)"));
                
            }
            
            rs=state.executeQuery("select avg(rate) from rating,book where bookid=b_id and u_id='"+u+"' AND genre='COMICS' group by genre");
            if(rs.next())
            {
                Double a=Double.parseDouble(rs.getString("avg(rate)"));
                double ma=a*20;
                int aa=(int)Math.round(ma);
                
                jSlider7.setValue(aa);
                jLabel41.setText(rs.getString("avg(rate)"));
                
            }
            
            
            
        }
    }catch(Exception e)
    {
        JOptionPane.showMessageDialog(null,e);
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        conn = Jdbc.ConnecrDb();
        String a=Login.user_id.getText();
        
        try{
                if(conn!=null)
                {
                    String u=Login.user_id.getText();
                    
                    Statement state=conn.createStatement();
                    
                    ResultSet rs=state.executeQuery("select username from users where userid='"+u+"'");    
                    if(rs.next())
                    {
                        a=rs.getString("username");
                    }
                    
                    welcome.setText(a);
                    jLabel55.setText(u);
                }
                
            
            }catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
    }//GEN-LAST:event_formWindowOpened

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        m.clear();
        list.setModel(m);
        conn = Jdbc.ConnecrDb();
        por1=0;nor1=0;
        jTextArea3.setText(" ");
        
        try{
            if(conn!=null)
            {

                Statement state=conn.createStatement();

                String sql="select * from book where bookname=?";
                pst=(OraclePreparedStatement) conn.prepareStatement(sql);
                pst.setString(1,text.getText());
                rs=(OracleResultSet) pst.executeQuery();
                if(rs.next()){
                    bookname.setText(text.getText());
                    bookid.setText(rs.getString("bookid"));
                    author.setText(rs.getString("author"));
                    genre.setText(rs.getString("genre"));
                    publisher.setText(rs.getString("publisher"));
                    edition.setText(rs.getString("edition"));
                    language.setText(rs.getString("language"));
                    
                
                }
                
                
                
                 String bi=bookid.getText();
                 sql="select CAST(AVG(RATE) as DECIMAL(10,2)) from rating where b_id=?";
                pst=(OraclePreparedStatement) conn.prepareStatement(sql);
                pst.setString(1,bookid.getText());
                rs=(OracleResultSet) pst.executeQuery();
                if(rs.next())
                    jLabel14.setText("AVERAGE RATING : "+rs.getString(1));
                
                sql="select count(rate) from rating where b_id=?";
                pst=(OraclePreparedStatement) conn.prepareStatement(sql);
                pst.setString(1,bookid.getText());
                rs=(OracleResultSet) pst.executeQuery();
                if(rs.next())
                    jLabel15.setText("TOTAL RATINGS : "+rs.getString(1));
                
                
               sql="SELECT U.USERNAME,R.COM FROM USERS U,RATING R WHERE U.USERID=R.U_ID AND R.B_ID=?";
                pst=(OraclePreparedStatement) conn.prepareStatement(sql);
                pst.setString(1,bookid.getText());
                rs=(OracleResultSet) pst.executeQuery(); 
                while(rs.next())
                {
                    por=0;nor=0;
                    String co=rs.getString("COM");
                    if(!(rs.getString("COM")==null))
                    {
                        jTextArea3.append(rs.getString("USERNAME")+"   :"+rs.getString("COM")+"\n");
                    }
                    String[] p   = {"good","wonderful","excellent","marvellous"};
                    String[] n ={"boring","bad","silly","gross"};
                    
                    String[] comment=null;
                    comment=co.split(" ");
                    answerQueries(comment, p);
                    answerQueries1(comment, n);
                     
                } 
                String count=Integer.toString(por1);
                String count1=Integer.toString(nor1);
                jLabel26.setText("POSITIVE REVIWES: "+count);
                jLabel27.setText("NEGATIVE REVIEWS: "+count1);
                //SELECT U.USERNAME,R.COM FROM USERS U,RATING R WHERE U.USERID=R.U_ID AND R.B_ID='C123';  
                
                if(por1==0&&nor1==0){
                jLabel26.setText("NO REVIEWS");
                jLabel27.setText("");
                }
            }
        }
        catch(Exception e)
        {
                
        }
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    public void search(String[]arr, String s) 
    { 
            int counter = 0; 
            for (int j = 0; j < arr.length; j++) 
  
                /* checking if string given in query is 
                  present in the given string. If present, 
                  increase times*/
                if (s.equals(arr[j]))
                {
                    por1++;
                    return;
                }    
            
    } 
    public void answerQueries(String[] arr, String q[]) 
    { 
        for (int i=0;i<q.length; i++) 
            search(arr, q[i]); 
    } 
    
    
     public void search1(String[]arr, String s) 
    { 
            int counter = 0; 
            for (int j = 0; j < arr.length; j++) 
  
                /* checking if string given in query is 
                  present in the given string. If present, 
                  increase times*/
                if (s.equals(arr[j]))
                {
                    nor1++;
                    return;
                }    
            
    } 
    public void answerQueries1(String[] arr, String q[]) 
    { 
        for (int i=0;i<q.length; i++) 
            search1(arr, q[i]); 
    } 
    
    
    private void publisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publisherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_publisherActionPerformed

    private void editionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editionActionPerformed

    private void textKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textKeyTyped
        
        conn = Jdbc.ConnecrDb();
        String u=Login.user_id.getText();
        String a=text.getText();
        m.clear();

        try{
            if(conn!=null)
            {

                Statement state=conn.createStatement();
                ResultSet rs=state.executeQuery("select bookname,author,edition from book where bookname not in(select b1.bookname from book b1,rating r1 where b1.bookid=r1.b_id and r1.u_id='"+u+"') and bookname like '"+a+"_%'");
                while(rs.next())
                {
                    m.addElement(rs.getString("bookname")+"  -  "+rs.getString("author")+"  [EDITION:"+rs.getString("edition")+"]" );
                    list.setModel(m);
                    list.setVisible(true);
                }
            }

        }catch(Exception e)
        {
                JOptionPane.showMessageDialog(null,e);
        }
        
    }//GEN-LAST:event_textKeyTyped

    private void textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textActionPerformed

    private void listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listMouseClicked
        String data=list.getSelectedValue();
        data=data.substring(0,data.indexOf("  -"));
        text.setText(data);
    }//GEN-LAST:event_listMouseClicked

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if(jCheckBox1.isSelected())
        {
            g1="DRAMA";
        }
        else
        {
            g1="AAA";
        }
        select();
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
       if(jCheckBox4.isSelected())
        {
            g4="CRIME";
        }
       else
        {
            g4="AAA";
        }
       select();
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
       if(jCheckBox5.isSelected())
        {
            g5="HISTORICAL";
        }
       else
        {
            g5="AAA";
        }
       select();
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        jRadioButton2.setSelected(false);
        select();
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
       jRadioButton1.setSelected(false);
       select();
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        model4=new DefaultTableModel();
        jTable3.setModel(model4);
        model4.addColumn("BOOKNAME");
        model4.addColumn("AUTHOR");
        model4.addColumn("GENRE");
        model4.addColumn("EDITION");
        g1="AAA";
        g2="AAA";
        g3="AAA";
        g4="AAA";
        g5="AAA";
        g6="AAA";
        o="ASC";
        home.setVisible(false);
        rate.setVisible(false);
        recommend.setVisible(false);
        user.setVisible(false);
        preference.setVisible(false);
        jPanel4.setVisible(true);
        jPanel7.setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        if(jCheckBox2.isSelected())
        {
            g2="POETRY";
        }
        else
        {
            g2="AAA";
        }
        select();
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        if(jCheckBox3.isSelected())
        {
            g3="HORROR";
        }
        else
        {
            g3="AAA";
        }
        select();
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox7ActionPerformed
        if(jCheckBox7.isSelected())
        {
            g6="COMICS";
        }
        else
        {
            g6="AAA";
        }
        select();
    }//GEN-LAST:event_jCheckBox7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        //model4.setRowCount(0);
        jPanel7.setVisible(true);
        model4=new DefaultTableModel();
        jTable3.setModel(model4);
        model4.addColumn("ISBN");
        model4.addColumn("BOOKNAME");
        model4.addColumn("AUTHOR");
        model4.addColumn("GENRE");
        model4.addColumn("EDITION");
        
         String u=Login.user_id.getText();
        conn = Jdbc.ConnecrDb();
         try{
            if(conn!=null)
        {
            int i=0;
            Statement state=conn.createStatement();
            if(jRadioButton2.isSelected())
            {
                o="DESC";
            }
            else
            {
                o="ASC";
            }
            
           
            ResultSet rs=state.executeQuery("select bookid,bookname,author,genre,edition from book \n" +
"where genre='"+g1+"' or genre='"+g2+"' or genre='"+g3+"' or genre='"+g4+"' or genre='"+g5+"' or genre='"+g6+"' order by bookname "+o+"");
            
           
           
            
            //ResultSet rs=state.executeQuery("select b.bookname,avg(r.rate) from book b,rating r where b.bookid=r.b_id and genre='"+g1+" OR GENRE='"+g4+"' group by b.bookname order by bookname "+o+" ");
            //where genre="+a+"
            while(rs.next()){
                model4.addRow(new Object[]{
                        rs.getString(1),
                        rs.getString(2),
                        rs.getString(3),
                        rs.getString(4),
                        rs.getString(5)
                        
                        
                        
                });
            }
        }
    }catch(Exception e)
    {
        
    }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        Login l=new Login();
        l.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        conn = Jdbc.ConnecrDb();
        try{
            int b=jSlider1.getValue();
            String rt=Integer.toString(b);
            PreparedStatement s=conn.prepareStatement("insert into rating values(?,?,?,?)");
            s.setString(1,Login.user_id.getText());
            s.setString(2,bookid.getText());
            s.setString(3,rt);
            s.setString(4,jTextField3.getText());
            s.executeUpdate();
            s=conn.prepareStatement("commit");
            s.executeUpdate();
            JOptionPane.showMessageDialog(null,"RATED");
            bookname.setText(null);
        bookid.setText(null);
        author.setText(null);
        genre.setText(null);
        publisher.setText(null);
        edition.setText(null);
        language.setText(null);
        text.setText(null);
        jSlider1.setValue(1);
        jLabel14.setText("AVERAGE RATING");
        jLabel15.setText("TOTAL RATINGS");
        jTextArea3.setText(null);
        jLabel26.setText("POSITIVE REVIEWS");
        jLabel27.setText("NEGATIVE REVIEWS");
        }catch(Exception e)
        {

        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        DefaultTableModel model =(DefaultTableModel)jTable3.getModel();
        int selectedRowIndex=jTable3.getSelectedRow();
        String bid=model.getValueAt(selectedRowIndex,0).toString();
        conn = Jdbc.ConnecrDb();
        
        
        try{
           Statement state=conn.createStatement();
           ResultSet rs=state.executeQuery("select count(rate) from rating where b_id='"+bid+"'");
            String count = null;
            if(rs.next()){
            jLabel49.setText(rs.getString(1));
            }
            
            
            rs=state.executeQuery("select count(rate) from rating where b_id='"+bid+"' and rate=1");
            if(rs.next()){
            jLabel50.setText(rs.getString(1));
            }
            
            rs=state.executeQuery("select count(rate) from rating where b_id='"+bid+"' and rate=2");
            if(rs.next()){
            jLabel51.setText(rs.getString(1));
            }
            
            rs=state.executeQuery("select count(rate) from rating where b_id='"+bid+"' and rate=3");
            if(rs.next()){
            jLabel52.setText(rs.getString(1));
            }
            
            rs=state.executeQuery("select count(rate) from rating where b_id='"+bid+"' and rate=4");
            if(rs.next()){
            jLabel53.setText(rs.getString(1));
            }
            rs=state.executeQuery("select count(rate) from rating where b_id='"+bid+"' and rate=5");
            if(rs.next()){
            jLabel54.setText(rs.getString(1));
            }
            
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_jTable3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userpanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userpanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userpanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userpanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userpanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField author;
    private javax.swing.JTextField bookid;
    private javax.swing.JTextField bookname;
    private javax.swing.JPanel centre;
    private javax.swing.JTextField edition;
    private javax.swing.JTextField genre;
    private javax.swing.JPanel home;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JProgressBar jSlider2;
    private javax.swing.JProgressBar jSlider3;
    private javax.swing.JProgressBar jSlider4;
    private javax.swing.JProgressBar jSlider5;
    private javax.swing.JProgressBar jSlider6;
    private javax.swing.JProgressBar jSlider7;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    public static javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField language;
    private javax.swing.JList<String> list;
    private javax.swing.JPanel preference;
    private javax.swing.JTextField publisher;
    private javax.swing.JPanel rate;
    private javax.swing.JPanel recommend;
    private javax.swing.JTextField text;
    private javax.swing.JPanel user;
    private javax.swing.JPanel viewbook;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
